server:
  port: 8082

jwt:
  token:
    secret-key: ENC(T7GiReOACR6VvUPXnRNLuFtRyUeqm2VxwotQPqY95cKutNa/czsRwcnL+LeUyIPoHkQJNOAL07s=)
    expTime: 1800000
    issuer: "jhkoder"


jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    bean: jasyptStringEncryptor

spring:
  output:
    ansi.enabled: always
  datasource:
    url: jdbc:oracle:thin:@commerce_high?TNS_ADMIN=C:\\Users\\Wallet_commerce
    username: admin
    password: ENC(naZ1jQTvsAHCN+6qJ1lD2xo85ywxaxll)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org:
      springframework:
        security: DEBUG