server:
  port: 8082

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    bean: jasyptStringEncryptor

jwt:
  token:
    secret-key: ENC(T7GiReOACR6VvUPXnRNLuFtRyUeqm2VxwotQPqY95cKutNa/czsRwcnL+LeUyIPoHkQJNOAL07s=)
    expTime: 1800000
    issuer: "jhkoder"

spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  output:
    ansi.enabled: always
  datasource:
    url: ENC(hDN6pZ+1KfaC9m91mpMBEmJXJp2QL5olPv9pZ8CVrCqWGV13YIfeAG7ih3uOJ8ObwzYJG0O4CzKkFF+czDl++yRIuhkpksNY/b1QgqR3wm4=)
    username: ENC(tDIsfFk29dW2FPV1YRU7jQ==)
    password: ENC(337YBU7IcDGvqzAIVHiTdG3DYmU1vKCz)
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(j7z7KrhuiBMRFQZBtmcSjp/Vmr2A48pVc3U2VWJ8Jr4=)
    password: ENC(tfrWr6m2T+j1gpJryewo5ymJ/Sve+p2kIew0NZS5AH0=)
    transport:
      protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
logging:
  level:
    org.hibernate.type.descriptor.sql: trace

cloud:
  image-repository:
    host: ENC(0NPhRpQb31rBd4E7T8AeE1SywEmUUjMd)
    username: ENC(krC61j79sImwc1t11M1Rjg==)
    ppk-path: ENC(3lOCzODtJ0qGt14S1CxfAzC0qwE2Iwr2asnO+4RbMSikjZ7echSdZg==)
    folder-path: ENC(Az3HmKiT8LbB/mj08Ec4xEGadbkGnbOO)

sms:
  from: ENC(gl24yeMqbC5ADgctyV5bVPp+psfSFlhs)
  platform:
    apick:
      uri: https://apick.app/rest/send_sms
      api-key: ENC(1MyGqdH8q5Pg6whdwGxEP0C/4tr5R9dlitvx43OIJAcabmmGN6Ip9INy/t+sH/xd)
      # 추가 ip 허용할떄 https://apick.app/my_page 여기서 추가

